# Generated by Django 5.1.3 on 2024-12-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySiteApp', '0003_users_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
