# Generated by Django 5.1.3 on 2024-12-11 09:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySiteApp', '0004_user_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phases',
            old_name='p_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='updates',
            name='project',
        ),
        migrations.RemoveField(
            model_name='updates',
            name='update_id',
        ),
        migrations.AddField(
            model_name='phases',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phases',
            name='title',
            field=models.CharField(default='Default Phase Title', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='due_date',
            field=models.DateField(default='2024-12-31'),
        ),
        migrations.AddField(
            model_name='updates',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='updates',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='updates',
            name='phase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='MySiteApp.phases'),
        ),
        migrations.AlterField(
            model_name='phases',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='MySiteApp.project'),
        ),
        migrations.AlterField(
            model_name='phases',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
