# Generated by Django 5.1.3 on 2024-12-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySiteApp', '0006_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('in-progress', 'In Progress'), ('completed', 'Completed'), ('not-started', 'Not Started')], default='not-started', max_length=20),
        ),
    ]
