# Generated by Django 5.1.3 on 2024-12-12 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySiteApp', '0009_remove_project_user_phases_mentor_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='assigned_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
