# Generated by Django 4.2.7 on 2025-10-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySiteApp', '0013_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_table',
            name='email',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
